name: publish

# Triggers when a new release is created
on:
  release:
    types: [published]

jobs:
  publish_plugin:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Publish the plugin to Gradle Plugin Portal (key and secret are stored as secrets in the repo)
    - name: Gradle publishPlugins
      run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
